# Generated by Django 6.1.1 on 2026-09-28 19:24

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0002_invoice_payment_reference"),
        ("tenancy", "0002_organization_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Calendar/fiscal year for this sequence partition."
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Last successfully issued sequential invoice number for this organization and year.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Sequence",
                "verbose_name_plural": "Invoice Sequences",
                "db_table": "invoice_sequences",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="unique_invoicing_invoicesequence_tenant_id",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "year"), name="unique_org_year_invoice_sequence"
                    ),
                ],
            },
        ),
    ]
