# Generated by Django 6.1.1 on 2026-09-30 10:47

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0003_invoicesequence"),
        ("ledger", "0001_initial"),
        ("tenancy", "0002_organization_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "credit_note_number",
                    models.CharField(
                        help_text="Tenant-scoped sequential identifier e.g. CN-2026-00001",
                        max_length=50,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Statutory date of credit note issuance.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Commercial or statutory reason for issuance."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("CLEARED", "Cleared"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ISSUED",
                        max_length=30,
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Subtotal / net sales returns before tax levies.",
                        max_digits=18,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="15.0% Standard VAT Output reversal.",
                        max_digits=18,
                    ),
                ),
                (
                    "nhil_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="2.5% NHIL Output reversal.",
                        max_digits=18,
                    ),
                ),
                (
                    "getfund_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="2.5% GETFund Output reversal.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Total statutory credit amount.",
                        max_digits=18,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Immutable legal name of customer at credit note issuance.",
                        max_length=255,
                    ),
                ),
                (
                    "customer_tin",
                    models.CharField(
                        blank=True, help_text="Immutable customer TIN at issuance.", max_length=20
                    ),
                ),
                (
                    "customer_ghana_card",
                    models.CharField(
                        blank=True,
                        help_text="Immutable customer Ghana Card PIN at issuance.",
                        max_length=25,
                    ),
                ),
                (
                    "customer_address",
                    models.TextField(
                        blank=True, help_text="Immutable customer billing address at issuance."
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                ("customer_email", models.CharField(blank=True, max_length=255)),
                (
                    "snapshot_frozen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the customer legal snapshot was permanently frozen.",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer recipient of the credit note.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="invoicing.contact",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Original invoice against which this credit note is issued.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Balanced reversing journal entry posted to general ledger.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_notes",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note",
                "verbose_name_plural": "Credit Notes",
                "db_table": "credit_notes",
                "ordering": ["-issue_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditNoteLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of credited goods/services.", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("1.0000"), max_digits=12),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "line_total",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.1500"), max_digits=6),
                ),
                (
                    "nhil_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0250"), max_digits=6),
                ),
                (
                    "getfund_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0250"), max_digits=6),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                (
                    "nhil_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                (
                    "getfund_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Revenue account to be debited (defaults to 4000 Sales Revenue / Returns).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ledger.chartofaccounts",
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        help_text="Parent credit note.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoicing.creditnote",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note Line",
                "verbose_name_plural": "Credit Note Lines",
                "db_table": "credit_note_lines",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditNoteSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(help_text="Calendar year governing this sequence."),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, help_text="Highest sequence allocated."),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note Sequence",
                "verbose_name_plural": "Credit Note Sequences",
                "db_table": "credit_note_sequences",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_invoicing_creditnote_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                fields=("organization", "credit_note_number"), name="unique_org_credit_note_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_amount__gte", Decimal("0.0000"))),
                name="credit_note_check_subtotal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", Decimal("0.0000"))),
                name="credit_note_check_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_invoicing_creditnoteline_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0.0000"))),
                name="credit_note_line_check_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", Decimal("0.0000"))),
                name="credit_note_line_check_unit_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", Decimal("0.0000"))),
                name="credit_note_line_check_line_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnotesequence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_invoicing_creditnotesequence_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnotesequence",
            constraint=models.UniqueConstraint(
                fields=("organization", "year"), name="unique_org_credit_note_sequence_year"
            ),
        ),
    ]
