# Generated by Django 6.1.1 on 2026-09-30 11:23

from django.db import migrations

import apps.core.fields


def encrypt_existing_contact_pii(apps, schema_editor):
    from apps.core.fields import get_fernet

    Contact = apps.get_model("invoicing", "Contact")
    fernet = get_fernet()

    for contact in Contact.objects.all():
        updated = False
        update_fields = []
        if contact.tin and not contact.tin.startswith("gAAAAA"):
            contact.tin = fernet.encrypt(contact.tin.encode("utf-8")).decode("utf-8")
            update_fields.append("tin")
            updated = True
        if contact.ghana_card_number and not contact.ghana_card_number.startswith("gAAAAA"):
            contact.ghana_card_number = fernet.encrypt(
                contact.ghana_card_number.encode("utf-8")
            ).decode("utf-8")
            update_fields.append("ghana_card_number")
            updated = True
        if updated:
            contact.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0004_creditnote_creditnoteline_creditnotesequence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="ghana_card_number",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Ghana Card National ID PIN (e.g. GHA-123456789-0).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tin",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Ghanaian Taxpayer Identification Number (e.g. C0001234567).",
                max_length=255,
            ),
        ),
        migrations.RunPython(encrypt_existing_contact_pii, reverse_code=migrations.RunPython.noop),
    ]
