# Generated by Django 6.1.1 on 2026-09-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Soft-deactivation status preserving statutory records for 6-year retention.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="settlement_account_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Account number for merchant bank settlements.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="settlement_bank_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Commercial bank name for merchant revenue settlements.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="settlement_locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when financial destination coordinates were last locked/modified.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="settlement_momo_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Merchant Mobile Money wallet phone number for automated settlements.",
                max_length=30,
            ),
        ),
    ]
