# Generated by Django 6.1.1 on 2026-09-30 11:23

import django.core.validators
from django.db import migrations, models

import apps.core.fields


def encrypt_existing_organization_pii(apps, schema_editor):
    import hashlib

    from apps.core.fields import get_fernet

    Organization = apps.get_model("tenancy", "Organization")
    fernet = get_fernet()

    for org in Organization.objects.all():
        updated = False
        update_fields = []
        if org.business_tin:
            cleaned = org.business_tin.strip().upper()
            org.business_tin_hash = hashlib.sha256(cleaned.encode("utf-8")).hexdigest()
            update_fields.append("business_tin_hash")
            if not org.business_tin.startswith("gAAAAA"):
                org.business_tin = fernet.encrypt(org.business_tin.encode("utf-8")).decode("utf-8")
                update_fields.append("business_tin")
            updated = True
        if org.ghana_card_number and not org.ghana_card_number.startswith("gAAAAA"):
            org.ghana_card_number = fernet.encrypt(org.ghana_card_number.encode("utf-8")).decode(
                "utf-8"
            )
            update_fields.append("ghana_card_number")
            updated = True
        if updated:
            org.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_organization_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="business_tin_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deterministic SHA-256 blind index for unique TIN lookups.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="business_tin",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="GRA Taxpayer Identification Number (e.g. C0001234567)",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid GRA Taxpayer Identification Number (e.g., C0001234567).",
                        regex="^[CPGVT]\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="ghana_card_number",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Director's Ghana Card PIN (e.g. GHA-123456789-0)",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Director Ghana Card PIN (e.g., GHA-123456789-0).",
                        regex="^GHA-\\d{9}-\\d$",
                    )
                ],
            ),
        ),
        migrations.RunPython(
            encrypt_existing_organization_pii, reverse_code=migrations.RunPython.noop
        ),
    ]
