import Link from "next/link";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#f8f9fa] text-[#1e293b] py-12 px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl border border-[#c3c6d7] p-8 md:p-12 shadow-sm">
        <div className="mb-8 border-b border-[#e2e8f0] pb-6">
          <Link
            href="/dashboard"
            className="text-xs font-semibold text-[#2563eb] hover:underline mb-4 inline-block"
          >
            &larr; Back to Dashboard
          </Link>
          <h1 className="text-3xl font-extrabold text-[#0f172a] tracking-tight">
            Privacy Policy &amp; Data Protection
          </h1>
          <p className="text-sm text-[#64748b] mt-2">
            Last Updated: September 30, 2026 &bull; Ghana Data Protection Commission (DPC) Compliant
          </p>
        </div>

        <div className="space-y-6 text-sm leading-relaxed text-[#334155]">
          <section>
            <h2 className="text-lg font-bold text-[#0f172a] mb-2">1. Statutory Framework</h2>
            <p>
              MageBooks processes financial, transactional, and personal data in strict compliance
              with the Ghana Data Protection Act, 2012 (Act 843) and regulations issued by the
              Data Protection Commission (DPC) of Ghana. We are committed to protecting the privacy
              and integrity of small business accounting and taxpayer data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#0f172a] mb-2">2. Multi-Tenant Cryptographic Isolation</h2>
            <p>
              Every tenant organization operates within an isolated cryptographic boundary. All tenant
              data is partitioned using foreign key constraints, Row-Level Security, and tenant context
              middleware. Financial records, general ledger balances, and payroll schedules belonging
              to one enterprise are never accessible by other tenants.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#0f172a] mb-2">3. Ghana Revenue Authority (GRA) Invoicing</h2>
            <p>
              When issuing taxable sales invoices, MageBooks transmits statutory tax payloads
              (including Taxpayer Identification Numbers, invoice totals, and VAT breakdowns) to the
              GRA E-VAT Clearance API as mandated by the Value Added Tax Act, 2013 (Act 870) as amended.
              QR codes and cryptographic clearance signatures generated by GRA are securely archived
              for the statutory 6-year tax retention period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#0f172a] mb-2">4. Offline Data Protection</h2>
            <p>
              Offline invoice drafts and cached directory records stored within progressive web app
              (PWA) local databases are encrypted using AES-GCM 256-bit encryption. Cryptographic keys
              are bound to the active user session and wiped upon explicit logout.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#0f172a] mb-2">5. Contact &amp; Rights</h2>
            <p>
              To exercise your rights to data access, rectification, or withdrawal under Act 843,
              contact our Data Protection Officer at{" "}
              <a href="mailto:privacy@magebooks.com" className="text-[#2563eb] hover:underline">
                privacy@magebooks.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
