# Generated by Django 6.1.1 on 2026-09-26 21:49

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action identifier (e.g. PBC_AUDIT_PACKAGE_GENERATED, INVOICE_CLEARED).",
                        max_length=100,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Domain model or resource category affected (e.g. PBCPackage, Invoice).",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Identifier of the target entity (UUID or storage path).",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address initiating the transaction.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="Client user agent string for forensics."
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of record state before mutation (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of record state after mutation (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Cryptographic SHA-256 digest for manifest non-repudiation.",
                        max_length=64,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Object storage key or export path for compiled artifacts.",
                        max_length=512,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary contextual metadata (e.g. fiscal year, presigned URL expiry).",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User identity who initiated the audited operation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="unique_audit_audittrail_tenant_id"
                    )
                ],
            },
        ),
    ]
