# Generated by Django 6.1.1 on 2026-09-26 22:42

from decimal import Decimal

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("DISBURSED", "Disbursed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_gross_salary",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Aggregate gross employee compensation for the run.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_ssnit_employee",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Aggregate 5.5% employee Tier 1 SSNIT pre-tax statutory deduction.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_ssnit_employer",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Aggregate 13.0% employer Tier 1 SSNIT statutory expense contribution.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_paye_tax",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Aggregate graduated Ghanaian Pay-As-You-Earn withholding tax.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_net_payout",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Aggregate net funds payable to employee Mobile Money wallets / bank accounts.",
                        max_digits=18,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when run was transitioned from DRAFT to PENDING_APPROVAL.",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when checker successfully verified TOTP 2FA and approved run.",
                        null=True,
                    ),
                ),
                (
                    "disbursed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when payout worker disbursed funds to employees.",
                        null=True,
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        blank=True,
                        help_text="User (Owner or Admin) who authorized the payroll disbursement with TOTP 2FA.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Balanced double-entry journal entry recording expenses and liabilities.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_runs",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        help_text="User (Accountant or Bookkeeper) who initiated and drafted the payroll run.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="Fiscal period to which payroll expenses and statutory liabilities attach.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="ledger.fiscalperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run",
                "verbose_name_plural": "Payroll Runs",
                "db_table": "payroll_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(help_text="Full legal name of employee.", max_length=255),
                ),
                (
                    "employee_tin_or_ghana_card",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ghana Card PIN (GHA-...) or GRA Individual TIN.",
                        max_length=50,
                    ),
                ),
                (
                    "momo_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mobile Money phone number for automatic wallet disbursement.",
                        max_length=30,
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Agreed gross salary / wages for the period.",
                        max_digits=18,
                    ),
                ),
                (
                    "ssnit_employee",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="5.5% employee Tier 1 SSNIT pre-tax deduction.",
                        max_digits=18,
                    ),
                ),
                (
                    "ssnit_employer",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="13.0% employer Tier 1 SSNIT statutory expense contribution.",
                        max_digits=18,
                    ),
                ),
                (
                    "taxable_income",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Gross salary less employee SSNIT (5.5%).",
                        max_digits=18,
                    ),
                ),
                (
                    "paye_tax",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ghana graduated monthly PAYE tax calculation.",
                        max_digits=18,
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Net salary payable to employee (gross - ssnit_employee - paye_tax).",
                        max_digits=18,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        help_text="Parent payroll run.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Item",
                "verbose_name_plural": "Payroll Items",
                "db_table": "payroll_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollTwoFactorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        help_text="Base32 encoded RFC 6238 TOTP seed parameter.", max_length=64
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Flag indicating whether TOTP 2FA is active."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Authorized user requiring step-up 2FA for payroll approvals.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_2fa_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll 2FA Profile",
                "verbose_name_plural": "Payroll 2FA Profiles",
                "db_table": "payroll_2fa_profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_payroll_payrollrun_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_payroll_payrollitem_tenant_id"
            ),
        ),
    ]
