# Generated by Django 6.1.1 on 2026-09-30 11:23

from django.db import migrations

import apps.core.fields


def encrypt_existing_payroll_pii(apps, schema_editor):
    from apps.core.fields import get_fernet

    PayrollItem = apps.get_model("payroll", "PayrollItem")
    fernet = get_fernet()

    for item in PayrollItem.objects.all():
        if item.employee_tin_or_ghana_card and not item.employee_tin_or_ghana_card.startswith(
            "gAAAAA"
        ):
            item.employee_tin_or_ghana_card = fernet.encrypt(
                item.employee_tin_or_ghana_card.encode("utf-8")
            ).decode("utf-8")
            item.save(update_fields=["employee_tin_or_ghana_card"])


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollitem",
            name="employee_tin_or_ghana_card",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Ghana Card PIN (GHA-...) or GRA Individual TIN.",
                max_length=255,
            ),
        ),
        migrations.RunPython(encrypt_existing_payroll_pii, reverse_code=migrations.RunPython.noop),
    ]
