# Generated by Django 6.1.1 on 2026-09-26 17:16

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0002_invoice_payment_reference"),
        ("ledger", "0001_initial"),
        ("payments", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentwebhooklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received"),
                    ("VERIFIED", "Signature Verified"),
                    ("FAILED_SIGNATURE", "Signature Verification Failed"),
                    ("FAILED_TENANT_RESOLUTION", "Failed Tenant Resolution"),
                    ("PROCESSED", "Processed"),
                    ("IGNORED", "Ignored"),
                ],
                db_index=True,
                default="RECEIVED",
                help_text="Current processing and verification status.",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, help_text="Gross transaction amount.", max_digits=18
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS", help_text="ISO 4217 currency code.", max_length=3
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MTN_MOMO", "MTN Mobile Money"),
                            ("TELECEL_CASH", "Telecel Cash"),
                            ("AT_MONEY", "AT Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("BANK_POS", "Bank POS Card"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="MTN_MOMO",
                        help_text="Payment channel or aggregator rail.",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("RECEIPT", "Receipt (Inflow)"), ("PAYMENT", "Payment (Outflow)")],
                        default="RECEIPT",
                        help_text="Direction of funds transfer.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SETTLED", "Settled"),
                            ("PARTIAL", "Partially Paid"),
                            ("SUSPENSE", "Suspense (Unreconciled)"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="SETTLED",
                        help_text="Current reconciliation and settlement status.",
                        max_length=30,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Aggregator transaction ID or bank reference code.",
                        max_length=100,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Customer-entered payment memo or Luhn invoice code.",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Effective timestamp of payment recognition.",
                    ),
                ),
                (
                    "reconciliation_notes",
                    models.TextField(blank=True, help_text="Audit and suspense routing memo."),
                ),
                (
                    "raw_event",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of normalized payment event payload.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User initiating transaction, or null for machine webhooks.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target customer contact record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="invoicing.contact",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target invoice settled by this payment receipt.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated double-entry general ledger journal entry.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-transaction_date", "-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="payments_organiz_6f226c_idx"
                    ),
                    models.Index(
                        fields=["organization", "payment_reference"],
                        name="payments_organiz_247bb5_idx",
                    ),
                    models.Index(
                        fields=["organization", "reference_number"],
                        name="payments_organiz_18eeec_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="unique_payments_payment_tenant_id"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="payment_amount_strictly_positive",
                    ),
                ],
            },
        ),
    ]
